### ISSUE TITLE
ccm v14.6.1 problem with xml profiles

### ISSUE THREAD

**Issue by seraf1** [quattor/CCM#22] opened 2014-09-29 07:18 UTC
With profile them xml, when we have an error, ccm respawns immediately, downloads a new profile and always finds a difference between the profiles.
So it raises ncm-ncd systematics, which leads to a saturation of the serve, the process rotating spma-yum permanently.

**Comment by jrha** [comment] 2015-01-06 11:24
Now we have #6 to discuss this we can get back on topic.
We should decide what we are going to do about this.

**Comment by jouvin** [comment] 2015-01-06 11:48
MS is clearly one site that depends heavily on XML profiles and I think we should fix the issue with them, we don't really have an alternative option... I'm pretty sure it's not a very tricky issue, the problem is to reproduce the problem when you have moved to JSON... Clearly we'll have to postpone it again...

**Comment by jrha** [comment] 2015-01-06 12:00
Agreed, but we should commit to fix it rather than continuing to put it off.

**Comment by jouvin** [comment] 2015-01-07 11:09
I just got access to a system exhibiting the problem... Hopefully, I'll be able to track down what happens. I already have a better picture:
* The problem happens after deployment of a new profile (even if the contents is the same)
* When it starts, every `ccm-fetch` attempt with a short interval with the previous one will trig the download of a new profile because the file on the server is considered newer than the last downloaded profile, despite the file timestamp on the server being older to the date reported by `ccm-fetch` in debug mode.
* If waiting enough time (~5-10 mn) between 2 `ccm-fetch` attempts, the problem is cleared (until detection of a newer profile following a new deployment)

This remains very strange for me, I'll see if last @stdweird fix https://github.com/quattor/CCM/commit/f49c48d141e680f481798a1018bcfcd65d9a9eb6 regarding date comparison may have something to do with the problem. But I really don't understand what is connected to XML in this problem... may be this is totally unrelated and we were fooled by the fact it happened with XML profiles and that moving to JSON had a "magic" impact...

**Comment by jouvin** [comment] 2015-01-07 11:30
Great news! The problem was due to this problem spotted and fixed by  @stdweird beginning of December where CTIME rather than MTIME was used for timestamp comparison (https://github.com/quattor/CCM/commit/f49c48d141e680f481798a1018bcfcd65d9a9eb6). With this fix backported to the machine exhibiting the problem (using Quattor 14.8.0), the problem is fixed.
I close the issue.

**Closed** 2015-01-07 11:30 UTC
Labels: bug

**Comment by ned21** [comment] 2015-01-07 11:39
Excellent news - many thanks.

**Comment by stdweird** [comment] 2015-01-07 12:26
@jouvin can you check how much the clocks of the http profile server and the client node differ? i think that is what is causing the issue. i just created https://github.com/quattor/CCM/issues/39 to help debugging any later issues.
